{{- if and .Values.public (ne .Values.platform.route "gateway") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.application.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ include "app.host" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.application.name }}
                port:
                  name: http
{{- end }}
